// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'G:/JAYANT/LatestProject/Rohit/HospitalManagement/02-03-2026/node_modules/@ant-design/icons/es/icons/SmileOutlined';
export default { SmileOutlined };
