// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/Projects/MSSPL/EIEHR_PROJECT/eiehrnew_ui/node_modules/@ant-design/icons/es/icons/SmileOutlined';
export default { SmileOutlined };
